name: japanese_history_app
description: "A new Flutter project."

publish_to: "none"

version: 1.2.3+42

environment:
  sdk: ^3.8.0

dependencies:
  package_info_plus: ^8.3.0
  sqflite: ^2.3.0
  intl: ^0.20.2
  shared_preferences: ^2.5.3
  url_launcher: ^6.1.10
  tutorial_coach_mark: ^1.2.11
  percent_indicator: ^4.2.5
  google_fonts: ^6.1.0

  fl_chart: ^0.71.0
  flutter:
    sdk: flutter
  path: ^1.8.0
  flutter_riverpod: ^2.0.0

  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  flutter_svg: ^2.1.0
  keyboard_actions: ^4.2.0

  cupertino_icons: ^1.0.8

  firebase_core: ^3.13.0
  path_provider: ^2.0.14
  firebase_auth: ^5.5.2
  firebase_analytics: ^11.4.5
  cloud_firestore: ^5.6.6
  rive: ^0.13.20
  ruby_text:
    git:
      url: https://github.com/Taniguchiyuto/RubyText.git
  flutter_native_splash: ^2.4.7
  firebase_storage: ^12.4.10
  cached_network_image: ^3.4.1
  hooks_riverpod: ^2.6.1
  firebase_crashlytics: ^4.3.10
  flutter_dotenv: ^6.0.0
  appsflyer_sdk: ^6.17.8
  cloud_functions: ^5.6.2
  page_transition: ^2.2.1
  open_mail_app_plus: ^0.0.2
  flutter_phoenix: ^1.1.1
  flutter_spinkit: ^5.2.2
  flutter_hooks: ^0.18.6
  flutter_inappwebview: ^6.1.5

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/Alan_spring.png"
  adaptive_icon_foreground: "assets/Alan_spring_Android.png"
  adaptive_icon_background: "#FFFFFF"

dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  flutter_test:
    sdk: flutter
  gap: ^3.0.1
  build_runner: ^2.5.4
  freezed: ^2.5.7
  json_serializable: ^6.7.1

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/notes/
    - assets/db/jap_his.db
    - .env

fonts:
  - family: SF Pro
    fonts:
      - asset: assets/fonts/SF-Pro-Text-Semibold.otf
        weight: 600

  - family: Hiragino Sans
    fonts:
      - asset: fonts/HiraginoSans-W6.otf
        weight: 600
      - asset: assets/fonts/HiraginoSans-W7.otf
        weight: 700
